### ISSUE TITLE
error for last stable version of 0.2.8

### ISSUE THREAD

**Issue by mwvoss** [NeuroimagingUIowa/xnat_downloader#48]
When trying to run last stable version (for example on TIVA) data, the following error occurs:

# command in terminal
```
sudo docker run \
-v /Volumes/vosslabhpc/Projects/TIVA/Imaging/BIDS:/json \
-v /Volumes/vosslabhpc/Projects/TIVA/Imaging/BIDS:/out  \
jdkent/xnat_downloader:v0.2.8 -i /json/download_config.json
```
# Terminal output
```
User: Traceback (most recent call last):
  File "/usr/local/miniconda/bin/xnat_downloader", line 11, in <module>
    load_entry_point('xnat-downloader==0.1', 'console_scripts', 'xnat_downloader')()
  File "/usr/local/miniconda/lib/python2.7/site-packages/xnat_downloader-0.1-py2.7.egg/xnat_downloader/cli/run.py", line 618, in main
    central = Interface(server=server)
  File "/usr/local/miniconda/lib/python2.7/site-packages/pyxnat/core/interfaces.py", line 174, in __init__
    user = input('User: ')
EOFError: EOF when reading a line
```

Is the above error expected for this version or is this a user error?

**Comment by jdkent** [comment]
This error results from xnat downloader (specifically pyxnat) expecting the user to input their username and password to log into xnat, but docker is being run non-interactively resulting in the above error.

The solution is to either make a credentials json file with username and password, [like here](https://github.com/NeuroimagingUIowa/xnat_downloader/blob/master/xnat_downloader/tests/data/central.cfg) and reference the credential file with the `-c` option in the xnat_downloader command or run docker interactively by changing the command like so:

```
sudo docker run -it \
-v /Volumes/vosslabhpc/Projects/TIVA/Imaging/BIDS:/json \
-v /Volumes/vosslabhpc/Projects/TIVA/Imaging/BIDS:/out  \
jdkent/xnat_downloader:v0.2.8 -i /json/download_config.json
```
Then you should be able to type your username and password when requested.
